---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  namespace: {{ include "ns" . }}
  labels:
    app: web-application
    component: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-application
      component: webapp
  template:
    metadata:
      labels:
        app: web-application
        component: webapp
    spec:
      containers:
      - name: diplom-netology
        image: "{{- .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: webapp-port
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport-svc
  namespace: {{ include "ns" . }}
  labels:
    app: web-application
    component: webapp
spec:
  type: NodePort
  selector:
    app: web-application
    component: webapp
  ports:
  - name: webapp-nodeport
    protocol: TCP
    nodePort: 30100
    port: 80
    targetPort: webapp-port
